import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Meme",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className} >
      <body className="flex flex-col bg-white min-h-screen">
        <header>
          <Navbar />
        </header>
        <main className="grow py-3">
          {children}
        </main>
        <footer className="py-3 text-center text-xs text-slate-500 text-2xl">Copyright 2024</footer>
      </body>
    </html>
  );
}
